# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('percentage', models.CharField(max_length=25)),
                ('price_old', models.CharField(max_length=25)),
                ('price_new', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=25)),
                ('website_region', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Website'),
        ),
    ]
