# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_product_is_favortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byPercentage', models.CharField(max_length=250)),
            ],
        ),
    ]
