# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_bypercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='byPercentage',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='discounts.ByPercentage'),
            preserve_default=False,
        ),
    ]
