# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_product_bypercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=250)),
                ('coupon_detail', models.CharField(max_length=2500)),
            ],
        ),
    ]
