# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
    ]
