# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20180113_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
    ]
