# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20180113_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_submit',
            field=models.CharField(default='kanak', max_length=250),
            preserve_default=False,
        ),
    ]
