# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_coupon_coupon_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_submit',
        ),
    ]
