# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_remove_coupon_coupon_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_link',
            field=models.CharField(default='timezone.now', max_length=2500),
            preserve_default=False,
        ),
    ]
