# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='discounts.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_available',
            field=models.IntegerField(default=170),
        ),
    ]
